%% Extract parameters from eegt structure to visualize
% -----------------------------------------------------------------------
% Input: 
% - eegt structure
% - task: task selected (name of the task)
% - analysis: name of the analysis

% Output:
% TextFromParams: cell array
% -----------------------------------------------------------------------

% --------------------------
% Author: Fecchio Matteo
% --------------------------

function [TextFromParams] = EEGgetTextFromParams(eegt,task,analysis)
parameters=eegt.tasks.(task).analyses.(analysis).parameters;

goodepochs=length(parameters.goodepochs);
if goodepochs==0; goodepochs=[]; end
goodch=length(parameters.goodchannels);
if goodch==0; goodch=[]; end
totcomp=length(parameters.ICA.comp2remove);
if totcomp==0; totcomp=[]; end
lowpass=parameters.filters.lowpass;
if isfield(parameters.filters2,'lowpass')
    lowpass=parameters.filters2.lowpass;
end

TextFromParams={['Sampling Rate: ' num2str(parameters.srate) ' Hz'];...
    ['Reference: ' parameters.ref];... 
    ['Epoch length: ' num2str(parameters.epochDuration) ' s'];...
    ['All Epochs: ' num2str(parameters.dimAllEvents)];...
    ['High pass: ' num2str(parameters.filters.highpass) ' Hz'];...
    ['Low Pass: ' num2str(lowpass) ' Hz'];...
    ['Band Stop: ' num2str(parameters.filters.bandstop) ' Hz'];...
    ['Good Epochs: ' num2str(goodepochs)];...
    ['Good Channels: ' num2str(goodch)];...
    ['ICA components: ' num2str(parameters.ICA.Cpca)];...
    ['ICA components removed: ' num2str(totcomp)];...
    ['PSD Reference: ' parameters.PSD.ref];...
    ['Epochs Stim ON: ' num2str(parameters.PSD.dimTrigONall)];...
    ['Epochs Stim OFF: ' num2str(parameters.PSD.dimTrigOFFall)];...
    ['SVM p-value: ' num2str(round(parameters.SVM.p_value_plus1*100)/100)];...
    ['SVM accuracy: ' num2str(round(parameters.SVM.accuracy*100)/100)];...
    ['SVM precision: ' num2str(round(parameters.SVM.precision*100)/100)];...
    ['SVM recall: ' num2str(round(parameters.SVM.recall*100)/100)];...
    };