function [testo] = EEGgetTextFromParams(eegt,task,analysis)
parameters=eegt.tasks.(task).analyses.(analysis).parameters;

goodepochs=length(parameters.goodepochs);
if goodepochs==0; goodepochs=[]; end
goodch=length(parameters.goodchannels);
if goodch==0; goodch=[]; end
totcomp=length(parameters.ICA.comp2remove);
if totcomp==0; totcomp=[]; end
lowpass=parameters.filters.lowpass;
if isfield(parameters.filters2,'lowpass')
    lowpass=parameters.filters2.lowpass;
end

testo={['Sampling Rate: ' num2str(parameters.srate) ' Hz'];...
    ['Reference: ' parameters.ref];... 
    ['Epoch length: ' num2str(parameters.epochDuration) ' s'];...
    ['All Epochs: ' num2str(parameters.dimAllEvents)];...
    ['High pass: ' num2str(parameters.filters.highpass) ' Hz'];...
    ['Low Pass: ' num2str(lowpass) ' Hz'];...
    ['Band Stop: ' num2str(parameters.filters.bandstop) ' Hz'];...
    ['Good Epochs: ' num2str(goodepochs)];...
    ['Good Channels: ' num2str(goodch)];...
    ['ICA components: ' num2str(parameters.ICA.Cpca)];...
    ['ICA components removed: ' num2str(totcomp)];...
    ['PSD Reference: ' parameters.PSD.ref];...
    ['Epochs Stim ON: ' num2str(parameters.PSD.dimTrigONall)];...
    ['Epochs Stim OFF: ' num2str(parameters.PSD.dimTrigOFFall)];...
    ['SVM p-value: ' num2str(parameters.SVM.p_value)];...
    ['SVM accuracy: ' num2str(parameters.SVM.accuracy)];...
    ['SVM precision: ' num2str(parameters.SVM.precision)];...
    ['SVM recall: ' num2str(parameters.SVM.recall)];...
%     ['SVM (with NaN) p-value: ' num2str(parameters.SVM_wn.p_value)];...
%     ['SVM (with NaN) accuracy: ' num2str(parameters.SVM_wn.accuracy)];...
    };